config/routes.rb
Simplecontactform::Application.routes.draw do
  root "home#index"
  
  resources "contacts", only: [:new, :create]

  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, :captcha => true

  #Declarate the e-mail headers. It accepts anything the mail method in ActionMailer accepts.
  #
  
  def headers
    {
    :subject => "My Contact Form",
    :to => "232516148@qip.ru",
    :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.haml
.container
  %h1 Thank you for your message.
  %p We'll get back to you soon.

app/views/contacts/new.html.haml
.container
  %h1 Contact
  = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
    = f.input :name, :required => true
    = f.input :email, :required => true
    = f.input :message, :as => :text, :required => false, :input_html => {:rows => 10}
    
    .hidden
      = f.input :nickname, :hint => 'Leave this field blank!'
    .form-actions
      = f.button :submit, 'Send message', :class=> "btn btn-primary"

app/views/home/index.html.haml
.container
  .row
    .span12
      %h1 Home#index
      %p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simplecontactform
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
  .container
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"}
            &times;
          = content_tag :div, msg, :id => "flash_#{name}"
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_url}
            brand
          .nav-collapse.collapse
            %ul.nav.pull-right
              %li
                = link_to t('Contact'), new_contact_path	
    = yield